ancil:
    class_name: lsst.cm.tools.db.script_handler.AncillaryScriptHandler
    collections:
    - /prod/calib/some_calib
    - /prod/calib/other_calib
    - /prod/skymaps
validate:
    class_name: lsst.cm.tools.db.script_handler.ValidateScriptHandler
    stamp: accepted
    fake: true
job:
    class_name: handler.ExampleJobHandler
workflow:
    class_name: lsst.cm.tools.db.workflow_handler.WorkflowHandler
    input_type: source
    output_type: run
    templates:
        coll_out: "{root_coll}/{fullname}_ouput"
    job_config: job
group:
    class_name: lsst.cm.tools.db.group_handler.GroupHandler
    input_type: tagged
    output_type: chained
    templates:
        coll_in: "{root_coll}/{fullname}_input"
        coll_out: "{root_coll}/{fullname}_ouput"
        coll_validate: "{root_coll}/{fullname}_validate"
step:
    input_type: source
    output_type: chained
    templates:
        coll_out: "{root_coll}/{fullname}_ouput"
        coll_validate: "{root_coll}/{fullname}_validate"
    scripts: [validate]
step1:
    class_name: handler.ExampleStep1Handler
    prerequisites: []
    pipeline_yaml: "${OBS_LSST_DIR}/pipelines/imsim/DRP.yaml#step1"
    includes: ["step"]
step2:
    class_name: handler.ExampleStep2Handler
    prerequisites: ['step1']
    pipeline_yaml: "${OBS_LSST_DIR}/pipelines/imsim/DRP.yaml#step2"
    includes: ["step"]
step3:
    class_name: handler.ExampleStep3Handler
    prerequisites: ['step2']
    pipeline_yaml: "${OBS_LSST_DIR}/pipelines/imsim/DRP.yaml#step3"
    includes: ["step"]
campaign:
    class_name: lsst.cm.tools.db.campaign_handler.CampaignHandler
    root_coll: 'cm'
    data_query: "instrument = 'HSC' and exposure < 500"
    input_type: tagged
    output_type: chained
    bps_yaml_template: "${CM_CONFIGS}/example_template.yaml"
    bps_script_template: "${CM_CONFIGS}/example_bps_template.sh"
    templates:
        coll_source: /prod/raw/all
        coll_in: "{root_coll}/{fullname}_input"
        coll_out: "{root_coll}/{fullname}_ouput"
        coll_ancil: "{root_coll}/{fullname}_ancil"
        coll_validate: "{root_coll}/{fullname}_validate"
    steps: ['step1', 'step2', 'step3']
